PORT=3005
RADIO_URL=https://vibez.bike-shed.io
GOOGLE_CLIENT_ID={{ op://infra/vibez/google-client-id }}
GOOGLE_CLIENT_SECRET={{ op://infra/vibez/google-client-secret }}
SESSION_SECRET={{ op://infra/vibez/session-secret }}
ADMIN_EMAILS={{ op://infra/vibez/admin-emails }}
BANNED_EMAILS={{ op://infra/vibez/banned-emails }}
SLACK_BOT_TOKEN={{ op://infra/vibez/slack-bot-token }}
SLACK_APP_TOKEN={{ op://infra/vibez/slack-app-token }}
SOUNDCLOUD_CLIENT_ID={{ op://infra/vibez/soundcloud-client-id }}
